### ISSUE TITLE
Providing emitZone is producing invalid JSON config file.

### ISSUE THREAD

**Issue by Waclaw-I** [koreezgames/phaser3-particle-editor#24]
Hi!

I was testing your particle editor and tried to import its output into my Phaser 3 game. Everything was fine untill I added an emitZone with shape defined.

## Expected Behavior

Editor should produce a valid JSON to use.

## Current Behavior

![zrzut ekranu 2018-09-12 o 12 13 19](https://user-images.githubusercontent.com/14911927/45418964-3112f900-b686-11e8-9cba-334610989023.png)

## Steps to Reproduce (for bugs)
[TestProject.zip](https://github.com/koreezgames/phaser3-particle-editor/files/2374663/TestProject.zip)
I also included .ppe file inside.

## Your Environment

- Version used: Phaser 3.12.0
- Environment name and version Chrome 68.0.3440.106
- Operating System and version (desktop or mobile): Desktop, Mac 10.12.6

Thanks for this awesome editor! I am really enjoying it.
Cheers!

**Comment by saqsun** [comment]
Hi @Waclaw-I !
Thanks for your report.

Actually this is an issue of readme and we should fix it ASAP ;)

Please try to do this:
```javascript
function preload() {
  this.load.atlas('shapes', 'assets/shapes.png', 'assets/shapes.json');
  this.load.text('particle-effect', 'assets/particle-effect.json');
}

function create() {
  this.add.particles('shapes',  new Function('return ' + this.cache.text.get('particle-effect'))());
}
```

Cheers!

**Comment by Waclaw-I** [comment]
Thanks for providing the solution @saqsun , working like charm!
