### ISSUE TITLE
Preview background image

### ISSUE THREAD

**Issue by PhaserEditor2D** [koreezgames/phaser3-particle-editor#27]
Add a background image for better preview.

## Expected Behavior

The user can upload an image to be set as the editor background. This may provide a better feedback to the user. The background image is not included in the "runtime", it is just for a preview purpose.

## Current Behavior

It shows one color background.

## Your Environment

- Version used:  v 1.0.0-beta1
- Chrome
- Linux

**Comment by PhaserEditor2D** [comment]
By the way, in addition, the editor can provide some built-in backgrounds, like a sea, a sky, a desert...

**Comment by saqsun** [comment]
Now you can do that!
https://koreezgames.github.io/phaser3-particle-editor/
