### ISSUE TITLE
[question] how to set particle's alpha as 0 when it is born?

### ISSUE THREAD

**Issue by jcyuan** [koreezgames/phaser3-particle-editor#40]
I'd like to have an effect: generate particle with alpha = 0, then fade in, then fade out...

**Comment by DblK** [comment]
A lot late, but I found the solution elsewhere.
Here is the code: 
```js
emitter.setAlpha(function (p, k, t) {
  return 1 - 2 * Math.abs(t - 0.5);
});
```
